var window = $global;
var document = $dom;

window.closed = $bool;
window.defaultStatus = $string;
window.document = $dom;
window.frames = [$dom];
window.history = $dom;
window.innerHeight = $int;
window.innerWidth = $int;
window.length = $int;
window.location = $dom;
window.name = $string;
window.navigator = $dom;
window.opener = $dom;
window.outerHeight = $int;
window.outerWidth = $int;
window.pageXOffset = $int;
window.pageYOffset = $int;
window.parent = $dom;
window.screen = $dom;
window.screenLeft = $int;
window.screenTop = $int;
window.screenX = $int;
window.screenY = $int;
window.self = window;
window.status = $string;
window.top = window || $dom;

window.alert = function(msg) {"" + msg;};
window.blur = function() {};
window.clearInterval = function(timer) {};
window.clearTimeout = function(timer) {};
window.close = function() {};
window.confirm = function(msg) {"" + msg; return $bool;};
window.createPopup = function() { return $dom; };
window.focus = function() {};
window.moveBy = function(dx,dy) {1+dx; 1+dy;};
window.moveTo = function(x,y) {1+x; 1+y;};
window.open = function(url,name,specs,replace) {
	""+url;
	""+name;
	""+specs;
	return $dom;
};
window.print = function() {};
window.prompt = function(msg,defaultText) {""+msg; ""+defaultText; return $string;};
window.resizeBy = function(w,h) {1+w; 1+h;};
window.resizeTo = function(w,h) {1+w; 1+h;};
window.scroll = function() {};
window.scrollBy = function(x,y) {1+x; 1+y;};
window.scrollTo = function(x,y) {1+x; 1+y;};
window.setInterval = function(f,time) {1+time; f(); return $dom;};
window.setTimeout = function(f,time) {1+time; f(); return $dom;};

window.console = $dom;

window.addEventListener = $dom;
window.removeEventListener = $dom;
window.captureEvents = $dom;
window.releaseEvents = $dom;
window.attachEvent = $dom;

window.HTMLButtonElement = $dom;
window.HTMLTableColElement = $dom;
window.HTMLOptionElement = $dom;
window.HTMLInputElement = $dom;
window.HTMLLinkElement = $dom;
window.HTMLTableElement = $dom;
window.HTMLHRElement = $dom;
window.HTMLProgressElement = $dom;
window.HTMLDivElement = $dom;
window.HTMLObjectElement = $dom;
window.HTMLFontElement = $dom;
window.HTMLHeadElement = $dom;
window.HTMLFieldSetElement = $dom;
window.HTMLVideoElement = $dom;
window.HTMLTableRowElement = $dom;
window.HTMLDListElement = $dom;
window.HTMLParamElement = $dom;
window.HTMLModElement = $dom;
window.HTMLOutputElement = $dom;
window.HTMLStyleElement = $dom;
window.HTMLBaseElement = $dom;
window.HTMLBRElement = $dom;
window.HTMLHtmlElement = $dom;
window.HTMLTextAreaElement = $dom;
window.HTMLBaseFontElement = $dom;
window.HTMLCanvasElement = $dom;
window.HTMLFrameElement = $dom;
window.HTMLElement = $dom;
window.HTMLSelectElement = $dom;
window.HTMLIsIndexElement = $dom;
window.HTMLDocument = $dom;
window.HTMLCollection = $dom;
window.HTMLDirectoryElement = $dom;
window.HTMLScriptElement = $dom;
window.HTMLOptGroupElement = $dom;
window.HTMLKeygenElement = $dom;
window.HTMLAreaElement = $dom;
window.HTMLFrameSetElement = $dom;
window.HTMLIFrameElement = $dom;
window.HTMLPreElement = $dom;
window.HTMLOListElement = $dom;
window.HTMLFormElement = $dom;
window.HTMLMediaElement = $dom;
window.HTMLHeadingElement = $dom;
window.HTMLMeterElement = $dom;
window.HTMLAppletElement = $dom;
window.HTMLMarqueeElement = $dom;
window.HTMLTableSectionElement = $dom;
window.HTMLTableCellElement = $dom;
window.HTMLMapElement = $dom;
window.HTMLLIElement = $dom;
window.HTMLParagraphElement = $dom;
window.HTMLBlockquoteElement = $dom;
window.HTMLUListElement = $dom;
window.HTMLEmbedElement = $dom;
window.HTMLBodyElement = $dom;
window.HTMLAudioElement = $dom;
window.HTMLTableCaptionElement = $dom;
window.HTMLMenuElement = $dom;
window.HTMLImageElement = $dom;
window.HTMLLabelElement = $dom;
window.HTMLAnchorElement = $dom;
window.HTMLMetaElement = $dom;

window.Image = $dom;
window.Element = $dom;
window.Option = $dom;
window.Text = $dom;
window.Document = $dom;
window.MimeType = $dom;
window.Plugin = $dom;
window.StyleSheet = $dom;
window.Comment = $dom;
window.Audio = $dom;
window.FormData = $dom;

window.onmouseup.apply(window,[$dom]);
window.onsubmit.apply(window,[$dom]);
window.onemptied.apply(window,[$dom]);
window.onpageshow.apply(window,[$dom]);
window.onstorage.apply(window,[$dom]);
window.oninvalid.apply(window,[$dom]);
window.onmousedown.apply(window,[$dom]);
window.onkeydown.apply(window,[$dom]);
window.onkeyup.apply(window,[$dom]);
window.onmessage.apply(window,[$dom]);
window.onunload.apply(window,[$dom]);
window.onseeked.apply(window,[$dom]);
window.ondragend.apply(window,[$dom]);
window.onended.apply(window,[$dom]);
window.onstalled.apply(window,[$dom]);
window.onvolumechange.apply(window,[$dom]);
window.ondragenter.apply(window,[$dom]);
window.onpagehide.apply(window,[$dom]);
window.onmouseover.apply(window,[$dom]);
window.ondragstart.apply(window,[$dom]);
window.onabort.apply(window,[$dom]);
window.oninput.apply(window,[$dom]);
window.onbeforeunload.apply(window,[$dom]);
window.onloadstart.apply(window,[$dom]);
window.onplaying.apply(window,[$dom]);
window.onhashchange.apply(window,[$dom]);
window.onprogress.apply(window,[$dom]);
window.oncanplay.apply(window,[$dom]);
window.onloadedmetadata.apply(window,[$dom]);
window.ondurationchange.apply(window,[$dom]);
window.onseeking.apply(window,[$dom]);
window.ononline.apply(window,[$dom]);
window.onpause.apply(window,[$dom]);
window.ondragover.apply(window,[$dom]);
window.onloadeddata.apply(window,[$dom]);
window.onkeypress.apply(window,[$dom]);
window.onmouseout.apply(window,[$dom]);
window.onoffline.apply(window,[$dom]);
window.onload.apply(window,[$dom]);
window.ondragleave.apply(window,[$dom]);
window.onpopstate.apply(window,[$dom]);
window.ondblclick.apply(window,[$dom]);
window.onsuspend.apply(window,[$dom]);
window.oncanplaythrough.apply(window,[$dom]);
window.onreset.apply(window,[$dom]);
window.onratechange.apply(window,[$dom]);
window.onerror.apply(window,[$dom]);
window.onplay.apply(window,[$dom]);
window.ontimeupdate.apply(window,[$dom]);
window.onwaiting.apply(window,[$dom]);
window.ondeviceorientation.apply(window,[$dom]);
window.onresize.apply(window,[$dom]);